Attempt to fix boost checksum issue with modified Podfile

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -38,7 +38,7 @@ workflows:
       - name: Skip code signing setup
         script: |
           echo "Building without code signing for simulator"
-      - name: Setup CocoaPods properly
+      - name: Fix boost checksum and setup CocoaPods
         script: | 
           cd apps/mobile-app/ios
           
@@ -53,8 +53,63 @@ workflows:
           # Install CocoaPods
           gem install cocoapods --no-document
           
-          # Install pods to create .xcworkspace
-          pod install --repo-update
+          # Clear all CocoaPods caches
+          pod cache clean --all
+          
+          # Try to fix the boost checksum issue by modifying Podfile
+          echo "Modifying Podfile to fix boost checksum issue..."
+          cat > Podfile << 'EOF'
+require_relative '../node_modules/react-native/scripts/react_native_pods'
+require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
+
+platform :ios, '17.0'
+prepare_react_native_project!
+
+# Specify the Xcode project
+project 'Thenga.xcodeproj'
+
+target 'Thenga' do
+  config = use_native_modules!
+
+  # Flags change depending on the env values.
+  flags = get_default_flags()
+
+  use_react_native!(
+    :path => config[:reactNativePath],
+    # Hermes is now enabled by default. Disable by setting this flag to false.
+    :hermes_enabled => flags[:hermes_enabled],
+    :fabric_enabled => flags[:fabric_enabled],
+    # Disable Flipper for now
+    :flipper_configuration => FlipperConfiguration.disabled,
+    # An absolute path to your application root.
+    :app_path => "#{Pod::Config.instance.installation_root}/.."
+  )
+
+  post_install do |installer|
+    react_native_post_install(
+      installer,
+      config[:reactNativePath],
+      :mac_catalyst_enabled => false
+    )
+    
+    # Fix boost checksum issue
+    installer.pods_project.targets.each do |target|
+      if target.name == 'boost'
+        target.build_configurations.each do |config|
+          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
+          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'BOOST_NO_CXX11_HDR_ARRAY=1'
+        end
+      end
+    end
+  end
+end
+EOF
+          
+          # Try installing with the modified Podfile
+          pod install --repo-update --verbose || {
+            echo "First attempt failed, trying with CDN..."
+            pod install --repo-update --verbose --use-modular-headers
+          }
           
           # Verify workspace was created
           echo "Checking for workspace file:"
