Fix YAML syntax error - use multiple fallback pod install methods

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -56,59 +56,14 @@ workflows:
           # Clear all CocoaPods caches
           pod cache clean --all
           
-          # Try to fix the boost checksum issue by modifying Podfile
-          echo "Modifying Podfile to fix boost checksum issue..."
-          cat > Podfile << 'EOF'
-require_relative '../node_modules/react-native/scripts/react_native_pods'
-require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
-
-platform :ios, '17.0'
-prepare_react_native_project!
-
-# Specify the Xcode project
-project 'Thenga.xcodeproj'
-
-target 'Thenga' do
-  config = use_native_modules!
-
-  # Flags change depending on the env values.
-  flags = get_default_flags()
-
-  use_react_native!(
-    :path => config[:reactNativePath],
-    # Hermes is now enabled by default. Disable by setting this flag to false.
-    :hermes_enabled => flags[:hermes_enabled],
-    :fabric_enabled => flags[:fabric_enabled],
-    # Disable Flipper for now
-    :flipper_configuration => FlipperConfiguration.disabled,
-    # An absolute path to your application root.
-    :app_path => "#{Pod::Config.instance.installation_root}/.."
-  )
-
-  post_install do |installer|
-    react_native_post_install(
-      installer,
-      config[:reactNativePath],
-      :mac_catalyst_enabled => false
-    )
-    
-    # Fix boost checksum issue
-    installer.pods_project.targets.each do |target|
-      if target.name == 'boost'
-        target.build_configurations.each do |config|
-          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
-          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'BOOST_NO_CXX11_HDR_ARRAY=1'
-        end
-      end
-    end
-  end
-end
-EOF
-          
-          # Try installing with the modified Podfile
+          # Try installing with existing Podfile first
+          echo "Attempting pod install with existing Podfile..."
           pod install --repo-update --verbose || {
-            echo "First attempt failed, trying with CDN..."
-            pod install --repo-update --verbose --use-modular-headers
+            echo "Standard install failed, trying with CDN..."
+            pod install --repo-update --verbose --use-modular-headers || {
+              echo "CDN install failed, trying with clean install..."
+              pod install --clean-install --repo-update --verbose
+            }
           }
           
           # Verify workspace was created
